name: OIB_TMSS_BACKEND_DB
services:
  mysql:
    image: mysql
    container_name: mysql_db
    env_file:
      - .env # Load environment variables from .env file
    ports:
      - "5001:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --socket=/tmp/mysql.sock
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--socket=/tmp/mysql.sock", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      start_period: 15s
      timeout: 5s
      retries: 100
    networks:
      - mysql_network

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge
